"""Machine-generated LaTeX number macros for the case-study prose.

Each ``casestudyN.py`` collects every number quoted in its section
(``paper/sections/casestudyN.tex``) into an ordered ``{name: value}`` mapping
and hands it to :func:`emit`, which writes
``paper/sections/csN_numbers.tex`` -- one ``\\newcommand`` per number.
The section ``\\input``s that file, so no case-study number is typed by hand.

Values are pre-formatted strings (the scripts round explicitly), so the file
content is deterministic.  ``emit(..., check=True)`` compares instead of
writing and returns a non-zero status on drift; ``check_cs_numbers.py`` runs
all four scripts in that mode (the CI drift gate).
"""
from __future__ import annotations

import re
import sys
from decimal import ROUND_HALF_UP, Decimal
from pathlib import Path

GEN_DIR = Path(__file__).resolve().parent.parent / "sections"

_NAME_RE = re.compile(r"^[A-Za-z]+$")


def fmt(value: float, ndigits: int) -> str:
    """Round half-up to ``ndigits`` decimals (e.g. 0.8125 -> '0.813').

    Uses the shortest repr of the float, so the result is deterministic and
    matches what a reader would round by hand.
    """
    q = Decimal(1).scaleb(-ndigits)
    return str(Decimal(repr(float(value))).quantize(q, rounding=ROUND_HALF_UP))


def pct(value: float, ndigits: int = 1) -> str:
    """Fraction -> percentage string, rounded half-up (0.8825 -> '88.3')."""
    return fmt(100.0 * float(value), ndigits)


def render(script: str, macros: dict[str, str]) -> str:
    """Return the macro-file content for ``macros`` (insertion order kept)."""
    lines = [
        f"% Auto-generated by paper/code/{script} -- do not edit.",
        f"% Regenerate: PYTHONPATH=scripts:paper/code python paper/code/{script}",
        f"% Drift gate: PYTHONPATH=scripts:paper/code python paper/code/check_cs_numbers.py",
    ]
    for name, value in macros.items():
        if not _NAME_RE.match(name):
            raise ValueError(f"macro name must be letters only: {name!r}")
        lines.append(f"\\newcommand{{\\{name}}}{{{value}}}")
    return "\n".join(lines) + "\n"


def emit(filename: str, script: str, macros: dict[str, str],
         check: bool = False) -> int:
    """Write (or, with ``check``, verify) ``GEN_DIR / filename``.

    Returns 0 when written or up to date, 1 when the committed file is stale.
    """
    path = GEN_DIR / filename
    content = render(script, macros)
    if check:
        if not path.exists() or path.read_text() != content:
            print(f"DRIFT: {path} is stale -- re-run paper/code/{script} "
                  "and commit.", file=sys.stderr)
            return 1
        print(f"{filename}: OK (no drift)")
        return 0
    GEN_DIR.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    print(f"Written {path}")
    return 0
