"""Generate paper/refs.bib from python/fdars/_references_map.json.

All entries use ``@misc`` (the map has no ``journal``, ``booktitle``, or
``publisher`` fields).  Uncurated placeholder entries (keys starting with
``_uncurated``) are skipped; exactly 47 curated/non-uncurated entries are
emitted.

Usage
-----
Generate mode (writes paper/refs.bib)::

    python paper/code/gen_refs_bib.py

Check mode (exits 1 if the committed file differs from a fresh derivation)::

    python paper/code/gen_refs_bib.py --check

The script is stdlib-only (``json``, ``pathlib``, ``sys``).  The cite-key for
each entry IS the paper-key verbatim — no name-parsing transformation is
applied.  Authors are joined with `` and ``.  Titles are double-braced
(``{{...}}``) to preserve case under ``\\bibliographystyle{plain}``.  Fields
(author, title, year, doi, url) are omitted when empty to avoid invalid
BibTeX like ``year = {None},`` or ``author = {}``.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

_REPO = Path(__file__).resolve().parent.parent.parent
_REF_MAP = _REPO / "python" / "fdars" / "_references_map.json"
_OUT = _REPO / "paper" / "refs.bib"

_HEADER = """\
% paper/refs.bib — auto-generated by paper/code/gen_refs_bib.py
% Source: python/fdars/_references_map.json
% Do not hand-edit; regenerate with: python paper/code/gen_refs_bib.py
"""


def _entry(key: str, paper: dict) -> str:
    """Format one BibTeX ``@misc`` entry block.

    Parameters
    ----------
    key : str
        BibTeX cite-key (verbatim paper-key from the references map).
    paper : dict
        Paper metadata dict containing ``authors``, ``title``, ``year``,
        and optionally ``doi``, ``url``, ``type``.

    Returns
    -------
    str
        Formatted ``@misc{...}`` block (no trailing newline).

    Notes
    -----
    Title is double-braced so ``\\bibliographystyle{plain}`` does not
    lowercase proper nouns.  ``doi`` and ``url`` are emitted only when
    non-empty (guards against the ``doi = {},`` empty-field BibTeX warning).
    """
    authors = " and ".join(paper.get("authors") or [])
    # Escape any literal braces in the title before double-bracing
    raw_title = paper.get("title") or ""
    title = raw_title.replace("{", r"\{").replace("}", r"\}")
    year = paper.get("year") or ""
    doi = paper.get("doi") or ""
    url = paper.get("url") or ""
    ptype = paper.get("type", "")

    lines = [f"@misc{{{key},"]
    if authors:
        lines.append(f"  author = {{{authors}}},")
    if title:
        lines.append(f"  title  = {{{{{title}}}}},")
    if year:
        lines.append(f"  year   = {{{year}}},")
    if doi:
        lines.append(f"  doi    = {{{doi}}},")
    if url:
        lines.append(f"  url    = {{{url}}},")
    if ptype:
        lines.append(f"  note   = {{Type: {ptype}}},")
    lines.append("}")
    return "\n".join(lines)


def _build_content() -> tuple[str, int, int]:
    """Load the references map and derive the full refs.bib content.

    Returns
    -------
    tuple[str, int, int]
        ``(content, n_entries, n_skipped)`` where *content* is the full file
        text, *n_entries* is the number of emitted entries, and *n_skipped*
        is the number of ``_uncurated`` entries that were omitted.
    """
    refs = json.loads(_REF_MAP.read_text())
    papers = refs.get("papers", {})

    entries = []
    skipped = 0
    for key in sorted(papers):
        if key.startswith("_uncurated"):
            skipped += 1
            continue
        entries.append(_entry(key, papers[key]))

    content = _HEADER + "\n\n".join(entries) + "\n"
    return content, len(entries), skipped


def main() -> None:
    """Entry point: generate or check refs.bib."""
    check_mode = "--check" in sys.argv
    content, n_entries, n_skipped = _build_content()

    if check_mode:
        if not _OUT.exists():
            print(
                f"DRIFT: {_OUT} does not exist — run without --check to generate.",
                file=sys.stderr,
            )
            sys.exit(1)
        committed = _OUT.read_text()
        if committed != content:
            print(
                f"DRIFT: {_OUT} is stale — re-run gen_refs_bib.py and commit.",
                file=sys.stderr,
            )
            sys.exit(1)
        print("gen_refs_bib: OK (no drift)")
    else:
        _OUT.write_text(content)
        print(f"Written {_OUT} ({n_entries} entries, {n_skipped} uncurated skipped)")


if __name__ == "__main__":
    main()
