"""Generate or check paper/snippets/*.tex from executed fdars snippets.

Each snippet runs REAL fdars code against a docs/data/ dataset, captures its
stdout, and emits a deterministic lstlisting fragment (source + output) that
the paper manuscript ``\\input``s.

Usage
-----
Generate mode (writes paper/snippets/*.tex)::

    PYTHONPATH=scripts:paper/code python paper/code/gen_snippets.py

Check mode (exits 1 if any committed fragment is stale or missing)::

    PYTHONPATH=scripts:paper/code python paper/code/gen_snippets.py --check

Macro set
---------
Generated fragments are consumed by ``paper/sections/capabilities.tex`` via
``\\input{snippets/<name>}``.  Each fragment contains:

- A static banner (no date/timestamp for byte-stable re-runs).
- A ``lstlisting[style=fdarsinput]`` block with the self-contained snippet
  source (imports included so readers can copy-paste).
- A ``lstlisting[style=fdarsoutput]`` block with the captured stdout, when
  the snippet produces non-empty output.

Determinism rules
-----------------
1. No timestamps in the banner — static text only.
2. Stochastic snippets seed ``np.random.seed`` before any random call.
3. Captured output uses shapes, dict keys, rounded scalars — never raw
   float arrays (platform-dependent repr).
4. Dict/list ordering: insertion-order-stable (Python 3.7+).
5. Single trailing ``\\n``, UTF-8, LF line endings.

Requires a compiled fdars (maturin develop) on PYTHONPATH.
"""
from __future__ import annotations

import io
import sys
import textwrap
from contextlib import redirect_stdout
from pathlib import Path

_SNIPPETS_DIR = Path(__file__).resolve().parent.parent / "snippets"
_BANNER = "% AUTO-GENERATED by paper/code/gen_snippets.py -- do not edit."


def _run(source: str, extra_ns: dict | None = None) -> str:
    """Exec *source* in a fresh namespace and return captured stdout verbatim.

    Parameters
    ----------
    source : str
        Python source code to execute.
    extra_ns : dict, optional
        Extra names injected into the execution namespace before exec (e.g.
        ``data_path`` from paper_utils so snippets use a robust data accessor).

    Returns
    -------
    str
        Captured stdout produced by the snippet (may be empty).
    """
    ns: dict = {}
    if extra_ns:
        ns.update(extra_ns)
    buf = io.StringIO()
    with redirect_stdout(buf):
        exec(compile(textwrap.dedent(source), "<snippet>", "exec"), ns)  # noqa: S102
    return buf.getvalue()


def _render(source: str, output: str) -> str:
    """Render snippet source + captured output as a LaTeX lstlisting fragment.

    Parameters
    ----------
    source : str
        Snippet source code (dedented; leading/trailing blank lines stripped).
    output : str
        Captured stdout (may be empty — output block is omitted if so).

    Returns
    -------
    str
        Full ``.tex`` fragment content ending with a single trailing newline.
        Byte-stable across runs (no timestamps, deterministic structure).
    """
    src = textwrap.dedent(source).strip("\n")
    lines = [
        _BANNER,
        r"\begin{lstlisting}[language=Python,style=fdarsinput]",
        src,
        r"\end{lstlisting}",
    ]
    if output.strip():
        lines += [
            r"\begin{lstlisting}[style=fdarsoutput]",
            output.rstrip("\n"),
            r"\end{lstlisting}",
        ]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Shared data-accessor injected into every snippet namespace so snippets are
# robust to cwd (PIPE-01 lock: no dataset copied into paper/).
# ---------------------------------------------------------------------------
from paper_utils import data_path as _data_path  # noqa: E402


_EXTRA_NS = {"data_path": _data_path}

# ---------------------------------------------------------------------------
# Snippet registry.
#
# Each entry: (name, source-code-string).
#
# Rules per RESEARCH.md §Determinism:
#   - Keep imports INSIDE the snippet body (self-contained, copy-pasteable).
#   - Use data_path("growth.csv") (injected into exec namespace).
#   - Avoid raw float arrays in print() — use shapes, keys, rounded scalars.
#   - Seed any stochastic call (np.random.seed / seed= kwarg).
#
# Wave-2 plans (88-02) will append additional family entries here.
# ---------------------------------------------------------------------------
SNIPPETS: list[tuple[str, str]] = [
    # ------------------------------------------------------------------
    # 1. Represent (data model) — tracer snippet for Phase 88 Plan 01.
    #    Validates the full harness path: script -> exec -> .tex -> \input.
    #    growth.csv: 31 ages x 93 subjects; .values.T -> (93 obs, 31 pts).
    # ------------------------------------------------------------------
    ("represent", """\
        import numpy as np, pandas as pd
        from fdars import Fdata
        growth = pd.read_csv(data_path("growth.csv"), index_col=0)
        ARG = growth.index.values.astype(float)
        X = growth.values.T.astype(np.float64)
        fd = Fdata(X, argvals=ARG, names={"x": "Age (years)", "y": "Height (cm)"})
        print(repr(fd))
        print("mean shape:", fd.mean().shape)
        """),
    # ------------------------------------------------------------------
    # 2. Basis / smoothing — fdata_to_basis_1d returns (coefs, nbasis) TUPLE;
    #    smooth_basis_gcv returns a dict.
    #    growth.csv setup: X (93, 31) float64, ARG len 31.
    # ------------------------------------------------------------------
    ("basis", """\
        import numpy as np, pandas as pd
        import fdars
        growth = pd.read_csv(data_path("growth.csv"), index_col=0)
        ARG = growth.index.values.astype(float)
        X = growth.values.T.astype(np.float64)
        res = fdars.basis.fdata_to_basis_1d(X[:5], ARG, n_basis=8, basis_type="bspline")
        coefs, nbasis = res
        print("coefficients shape:", coefs.shape, "| n_basis:", nbasis)
        sm = fdars.basis.smooth_basis_gcv(X[:5], ARG, n_basis=8, basis_type="bspline")
        print("smoothing keys:", list(sm.keys()))
        print("fitted shape:", sm["fitted"].shape)
        """),
    # ------------------------------------------------------------------
    # 3. Depth & outliers — use Fdata.depth() method (handles dtype);
    #    muod(data) takes NO argvals.
    # ------------------------------------------------------------------
    ("depth", """\
        import numpy as np, pandas as pd
        import fdars
        from fdars import Fdata
        growth = pd.read_csv(data_path("growth.csv"), index_col=0)
        ARG = growth.index.values.astype(float)
        X = growth.values.T.astype(np.float64)
        fd = Fdata(X, argvals=ARG)
        depths = fd.depth(method="fraiman_muniz")
        print("depths shape:", depths.shape, "| most central obs:", int(np.argmax(depths)))
        out = fdars.outliers.muod(X)
        print("shape outliers:", out["shape_outliers"], "| amplitude:", out["amplitude_outliers"])
        """),
    # ------------------------------------------------------------------
    # 4. FPCA (dense) + sparse/irregular PACE FPCA.
    #    This doubles as the MANU-05 irregular-representation snippet.
    #    pace_fpca.irreg_fdata_from_lists -> PyIrregFdata -> pace_fpca().
    # ------------------------------------------------------------------
    ("fpca", """\
        import numpy as np, pandas as pd
        import fdars
        from fdars import Fdata
        growth = pd.read_csv(data_path("growth.csv"), index_col=0)
        ARG = growth.index.values.astype(float)
        X = growth.values.T.astype(np.float64)
        fd = Fdata(X, argvals=ARG)
        pc = fd.to_pc(n_comp=3)
        print("FPCA scores shape:", pc["scores"].shape, "| singular values:", np.round(pc["singular_values"], 2).tolist())
        np.random.seed(42)
        argvals_list = [np.sort(np.random.uniform(1, 18, np.random.randint(5, 15))).tolist() for _ in range(30)]
        values_list = [np.sin(av).tolist() for av in argvals_list]
        irreg = fdars.pace_fpca.irreg_fdata_from_lists(argvals_list, values_list)
        pace = fdars.pace_fpca.pace_fpca(irreg, ncomp=2)
        print("PACE scores shape:", pace["scores"].shape, "| ncomp:", pace["ncomp"])
        """),
    # ------------------------------------------------------------------
    # 5. Clustering — kmeans_fd(data, argvals, k, seed=42); print
    #    cluster sizes (int list) and converged (bool), not float tot_withinss.
    # ------------------------------------------------------------------
    ("clustering", """\
        import numpy as np, pandas as pd
        import fdars
        growth = pd.read_csv(data_path("growth.csv"), index_col=0)
        ARG = growth.index.values.astype(float)
        X = growth.values.T.astype(np.float64)
        km = fdars.clustering.kmeans_fd(X, ARG, k=3, seed=42)
        print("cluster sizes:", np.bincount(km["cluster"]).tolist(), "| converged:", km["converged"])
        """),
    # ------------------------------------------------------------------
    # 6. Classification — fclassif_knn(data, labels, ncomp, k);
    #    labels MUST be int64 ndarray (not list, not uint32);
    #    phoneme.csv: 400 rows x 256 freq points, 5 classes in row index.
    # ------------------------------------------------------------------
    ("classification", """\
        import numpy as np, pandas as pd
        import fdars
        ph = pd.read_csv(data_path("phoneme.csv"), index_col=0)
        Xp = ph.values.astype(np.float64)
        labels_str = ph.index.tolist()
        uniq = list(dict.fromkeys(labels_str))
        lut = {l: i for i, l in enumerate(uniq)}
        y = np.array([lut[l] for l in labels_str], dtype=np.int64)
        res = fdars.classification.fclassif_knn(Xp[:100], y[:100], ncomp=3, k=5)
        print("accuracy:", res["accuracy"])
        """),
    # ------------------------------------------------------------------
    # 7. Regression (scalar-on-function) — fregre_lm(data, response, n_comp);
    #    tecator.csv: 240 x 103 (100 spectral channels + moisture/fat/protein).
    #    FoF regression (fof_regression) is available but mentioned in prose.
    # ------------------------------------------------------------------
    ("regression", """\
        import numpy as np, pandas as pd
        import fdars
        tec = pd.read_csv(data_path("tecator.csv"), index_col=0)
        Xt = tec.iloc[:, :100].values.astype(np.float64)
        yfat = tec["fat"].values.astype(np.float64)
        sof = fdars.regression.fregre_lm(Xt, yfat, n_comp=5)
        print("R^2:", round(sof["r_squared"], 4))
        """),
]


def main() -> None:
    """Entry point: generate or drift-check all snippet fragments."""
    check = "--check" in sys.argv
    _SNIPPETS_DIR.mkdir(parents=True, exist_ok=True)
    stale: list[str] = []

    for name, source in SNIPPETS:
        out = _run(source, extra_ns=_EXTRA_NS)
        content = _render(source, out)
        target = _SNIPPETS_DIR / f"{name}.tex"

        if check:
            if not target.exists() or target.read_text(encoding="utf-8") != content:
                stale.append(str(target))
        else:
            target.write_text(content, encoding="utf-8")

    if check:
        if stale:
            print(
                "DRIFT: stale/missing snippets -- re-run gen_snippets.py and commit:",
                file=sys.stderr,
            )
            for s in stale:
                print(f"  {s}", file=sys.stderr)
            sys.exit(1)
        print("gen_snippets: OK (no drift)")
    else:
        print(f"Wrote {len(SNIPPETS)} snippet fragment(s) to {_SNIPPETS_DIR}")


if __name__ == "__main__":
    main()
