"""Generate paper/refs.bib from python/fdars/_references_map.json.

The map records title/authors/year/DOI but no venue.  Venues (journal,
volume, pages, entry type) come from ``bib_venues.json``, a Crossref overlay
fetched once by ``fetch_bib_venues.py`` and committed, so this generator stays
offline.  Entries without a Crossref venue fall back to ``@misc``.  Two classes of record are skipped: uncurated
placeholder keys (starting with ``_uncurated``) and empty-payload stubs (no
``title``, ``authors``, or ``year`` — these can only emit a malformed
``@misc`` carrying a lone ``note``).  Exactly 46 entries are emitted.

Usage
-----
Generate mode (writes paper/refs.bib)::

    python paper/code/gen_refs_bib.py

Check mode (exits 1 if the committed file differs from a fresh derivation)::

    python paper/code/gen_refs_bib.py --check

The script is stdlib-only (``json``, ``pathlib``, ``sys``).  The cite-key for
each entry IS the paper-key verbatim — no name-parsing transformation is
applied.  Authors are joined with `` and ``.  Titles are double-braced
(``{{...}}``) to preserve case under ``\\bibliographystyle{plain}``.  Fields
(author, title, year, doi, url) are omitted when empty to avoid invalid
BibTeX like ``year = {None},`` or ``author = {}``.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

_REPO = Path(__file__).resolve().parent.parent.parent
_REF_MAP = _REPO / "python" / "fdars" / "_references_map.json"
_OUT = _REPO / "paper" / "refs.bib"
_VENUES = Path(__file__).resolve().parent / "bib_venues.json"

_HEADER = """\
% paper/refs.bib — auto-generated by paper/code/gen_refs_bib.py
% Source: python/fdars/_references_map.json
% Do not hand-edit; regenerate with: python paper/code/gen_refs_bib.py
"""


def _tex_escape(value: str) -> str:
    """Escape the LaTeX specials that occur in venue names (``&``)."""
    return value.replace("&", r"\&")


def _entry(key: str, paper: dict, venue: dict | None = None) -> str:
    """Format one BibTeX entry block.

    Parameters
    ----------
    key : str
        BibTeX cite-key (verbatim paper-key from the references map).
    paper : dict
        Paper metadata dict containing ``authors``, ``title``, ``year``,
        and optionally ``doi`` and ``url``.
    venue : dict, optional
        Crossref-derived venue overlay from ``bib_venues.json`` (entry type,
        journal/booktitle, volume, number, pages, publisher).  Without it the
        entry falls back to ``@misc``.

    Returns
    -------
    str
        Formatted entry block (no trailing newline).

    Notes
    -----
    Title is double-braced so the bibliography style does not lowercase proper
    nouns.  Empty fields are omitted.  The DOI is preferred over the URL: the
    URL is emitted only when no DOI exists (e.g. arXiv-only preprints), which
    keeps each rendered reference to a single resolvable identifier.
    """
    venue = venue or {}
    etype = venue.get("entry_type", "misc")
    authors = " and ".join(paper.get("authors") or [])
    raw_title = paper.get("title") or ""
    title = raw_title.replace("{", r"\{").replace("}", r"\}")
    year = paper.get("year") or ""
    doi = paper.get("doi") or ""
    url = paper.get("url") or ""

    lines = [f"@{etype}{{{key},"]
    if authors:
        lines.append(f"  author    = {{{authors}}},")
    if title:
        lines.append(f"  title     = {{{{{title}}}}},")
    for field in ("journal", "booktitle", "volume", "number", "pages", "publisher"):
        if venue.get(field):
            lines.append(f"  {field:<9} = {{{_tex_escape(venue[field])}}},")
    if year:
        lines.append(f"  year      = {{{year}}},")
    if doi:
        lines.append(f"  doi       = {{{doi}}},")
    elif url:
        lines.append(f"  url       = {{{url}}},")
    lines.append("}")
    return "\n".join(lines)


def _build_content() -> tuple[str, int, int]:
    """Load the references map and derive the full refs.bib content.

    Returns
    -------
    tuple[str, int, int]
        ``(content, n_entries, n_skipped)`` where *content* is the full file
        text, *n_entries* is the number of emitted entries, and *n_skipped*
        is the number of ``_uncurated`` entries that were omitted.
    """
    refs = json.loads(_REF_MAP.read_text())
    papers = refs.get("papers", {})
    venues = json.loads(_VENUES.read_text()) if _VENUES.exists() else {}

    entries = []
    skipped = 0
    for key in sorted(papers):
        if key.startswith("_uncurated"):
            skipped += 1
            continue
        paper = papers[key]
        # Skip records with no bibliographic payload (no title, author, or
        # year): they can only emit a malformed @misc carrying a lone note,
        # which is dead weight (never renders under \bibliographystyle{plain}
        # unless cited, and no such stub is cited).
        if not (paper.get("title") or paper.get("authors") or paper.get("year")):
            skipped += 1
            continue
        entries.append(_entry(key, paper, venues.get(key)))

    content = _HEADER + "\n\n".join(entries) + "\n"
    return content, len(entries), skipped


def main() -> None:
    """Entry point: generate or check refs.bib."""
    check_mode = "--check" in sys.argv
    content, n_entries, n_skipped = _build_content()

    if check_mode:
        if not _OUT.exists():
            print(
                f"DRIFT: {_OUT} does not exist — run without --check to generate.",
                file=sys.stderr,
            )
            sys.exit(1)
        committed = _OUT.read_text()
        if committed != content:
            print(
                f"DRIFT: {_OUT} is stale — re-run gen_refs_bib.py and commit.",
                file=sys.stderr,
            )
            sys.exit(1)
        print("gen_refs_bib: OK (no drift)")
    else:
        _OUT.write_text(content)
        print(f"Written {_OUT} ({n_entries} entries, {n_skipped} uncurated skipped)")


if __name__ == "__main__":
    main()
