"""Generate or check paper/snippets/*.tex from executed fdars snippets.

Each snippet runs REAL fdars code against a docs/data/ dataset, captures its
stdout, and emits a deterministic lstlisting fragment (source + output) that
the paper manuscript ``\\input``s.

Usage
-----
Generate mode (writes paper/snippets/*.tex)::

    PYTHONPATH=scripts:paper/code python paper/code/gen_snippets.py

Check mode (exits 1 if any committed fragment is stale or missing)::

    PYTHONPATH=scripts:paper/code python paper/code/gen_snippets.py --check

Macro set
---------
Generated fragments are consumed by ``paper/sections/capabilities.tex`` via
``\\input{snippets/<name>}``.  Each fragment contains:

- A static banner (no date/timestamp for byte-stable re-runs).
- A ``lstlisting[style=fdarsinput]`` block with the self-contained snippet
  source (imports included so readers can copy-paste).
- A ``lstlisting[style=fdarsoutput]`` block with the captured stdout, when
  the snippet produces non-empty output.

Determinism rules
-----------------
1. No timestamps in the banner — static text only.
2. Stochastic snippets seed ``np.random.seed`` before any random call.
3. Captured output uses shapes, dict keys, rounded scalars — never raw
   float arrays (platform-dependent repr).
4. Dict/list ordering: insertion-order-stable (Python 3.7+).
5. Single trailing ``\\n``, UTF-8, LF line endings.

Requires a compiled fdars (maturin develop) on PYTHONPATH.
"""
from __future__ import annotations

import io
import sys
import textwrap
from contextlib import redirect_stdout
from pathlib import Path

_SNIPPETS_DIR = Path(__file__).resolve().parent.parent / "snippets"
_BANNER = "% AUTO-GENERATED by paper/code/gen_snippets.py -- do not edit."


def _run(source: str, extra_ns: dict | None = None) -> str:
    """Exec *source* in a fresh namespace and return captured stdout verbatim.

    Parameters
    ----------
    source : str
        Python source code to execute.
    extra_ns : dict, optional
        Extra names injected into the execution namespace before exec (e.g.
        ``data_path`` from paper_utils so snippets use a robust data accessor).

    Returns
    -------
    str
        Captured stdout produced by the snippet (may be empty).
    """
    ns: dict = {}
    if extra_ns:
        ns.update(extra_ns)
    buf = io.StringIO()
    with redirect_stdout(buf):
        exec(compile(textwrap.dedent(source), "<snippet>", "exec"), ns)  # noqa: S102
    return buf.getvalue()


def _render(source: str, output: str) -> str:
    """Render snippet source + captured output as a LaTeX lstlisting fragment.

    Parameters
    ----------
    source : str
        Snippet source code (dedented; leading/trailing blank lines stripped).
    output : str
        Captured stdout (may be empty — output block is omitted if so).

    Returns
    -------
    str
        Full ``.tex`` fragment content ending with a single trailing newline.
        Byte-stable across runs (no timestamps, deterministic structure).
    """
    src = textwrap.dedent(source).strip("\n")
    lines = [
        _BANNER,
        r"\begin{lstlisting}[language=Python,style=fdarsinput]",
        src,
        r"\end{lstlisting}",
    ]
    if output.strip():
        lines += [
            r"\begin{lstlisting}[style=fdarsoutput]",
            output.rstrip("\n"),
            r"\end{lstlisting}",
        ]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Shared data-accessor injected into every snippet namespace so snippets are
# robust to cwd (PIPE-01 lock: no dataset copied into paper/).
# ---------------------------------------------------------------------------
from paper_utils import data_path as _data_path  # noqa: E402


_EXTRA_NS = {"data_path": _data_path}

# ---------------------------------------------------------------------------
# Snippet registry.
#
# Each entry: (name, source-code-string).
#
# Rules per RESEARCH.md §Determinism:
#   - Keep imports INSIDE the snippet body (self-contained, copy-pasteable).
#   - Use data_path("growth.csv") (injected into exec namespace).
#   - Avoid raw float arrays in print() — use shapes, keys, rounded scalars.
#   - Seed any stochastic call (np.random.seed / seed= kwarg).
#
# Wave-2 plans (88-02) will append additional family entries here.
# ---------------------------------------------------------------------------
SNIPPETS: list[tuple[str, str]] = [
    # ------------------------------------------------------------------
    # 1. Represent (data model) — tracer snippet for Phase 88 Plan 01.
    #    Validates the full harness path: script -> exec -> .tex -> \input.
    #    growth.csv: 31 ages x 93 subjects; .values.T -> (93 obs, 31 pts).
    # ------------------------------------------------------------------
    ("represent", """\
        import numpy as np, pandas as pd
        from fdars import Fdata
        growth = pd.read_csv(data_path("growth.csv"), index_col=0)
        ARG = growth.index.values.astype(float)
        X = growth.values.T.astype(np.float64)
        fd = Fdata(X, argvals=ARG, names={"x": "Age (years)", "y": "Height (cm)"})
        print(repr(fd))
        print("mean shape:", fd.mean().shape)
        """),
    # Wave-2 plans (88-02) will append remaining families here:
    # basis/smoothing, depth/outliers, fpca/pace, clustering, classification,
    # regression, fts, spm, tolerance, metric, alignment, advisor, sklearn.
]


def main() -> None:
    """Entry point: generate or drift-check all snippet fragments."""
    check = "--check" in sys.argv
    _SNIPPETS_DIR.mkdir(parents=True, exist_ok=True)
    stale: list[str] = []

    for name, source in SNIPPETS:
        out = _run(source, extra_ns=_EXTRA_NS)
        content = _render(source, out)
        target = _SNIPPETS_DIR / f"{name}.tex"

        if check:
            if not target.exists() or target.read_text(encoding="utf-8") != content:
                stale.append(str(target))
        else:
            target.write_text(content, encoding="utf-8")

    if check:
        if stale:
            print(
                "DRIFT: stale/missing snippets -- re-run gen_snippets.py and commit:",
                file=sys.stderr,
            )
            for s in stale:
                print(f"  {s}", file=sys.stderr)
            sys.exit(1)
        print("gen_snippets: OK (no drift)")
    else:
        print(f"Wrote {len(SNIPPETS)} snippet fragment(s) to {_SNIPPETS_DIR}")


if __name__ == "__main__":
    main()
