"""Generate paper/refs.bib from python/fdars/_references_map.json.

All entries use ``@misc`` (the map has no ``journal``, ``booktitle``, or
``publisher`` fields).  Uncurated placeholder entries (keys starting with
``_uncurated``) are skipped; exactly 47 curated/non-uncurated entries are
emitted.

Usage
-----
::

    python paper/code/gen_refs_bib.py

The script is stdlib-only (``json``, ``pathlib``, ``sys``).  The cite-key for
each entry IS the paper-key verbatim — no name-parsing transformation is
applied.  Authors are joined with `` and ``.  Titles are double-braced
(``{{...}}``) to preserve case under ``\\bibliographystyle{plain}``.  The
``doi`` and ``url`` lines are emitted only when non-empty.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

_REPO = Path(__file__).resolve().parent.parent.parent
_REF_MAP = _REPO / "python" / "fdars" / "_references_map.json"
_OUT = _REPO / "paper" / "refs.bib"

_HEADER = """\
% paper/refs.bib — auto-generated by paper/code/gen_refs_bib.py
% Source: python/fdars/_references_map.json
% Do not hand-edit; regenerate with: python paper/code/gen_refs_bib.py
"""


def _entry(key: str, paper: dict) -> str:
    """Format one BibTeX ``@misc`` entry block.

    Parameters
    ----------
    key : str
        BibTeX cite-key (verbatim paper-key from the references map).
    paper : dict
        Paper metadata dict containing ``authors``, ``title``, ``year``,
        and optionally ``doi``, ``url``, ``type``.

    Returns
    -------
    str
        Formatted ``@misc{...}`` block (no trailing newline).

    Notes
    -----
    Title is double-braced so ``\\bibliographystyle{plain}`` does not
    lowercase proper nouns.  ``doi`` and ``url`` are emitted only when
    non-empty (guards against the ``doi = {},`` empty-field BibTeX warning).
    """
    authors = " and ".join(paper.get("authors") or [])
    # Escape any literal braces in the title before double-bracing
    raw_title = paper.get("title") or ""
    title = raw_title.replace("{", r"\{").replace("}", r"\}")
    year = paper.get("year") or ""
    doi = paper.get("doi") or ""
    url = paper.get("url") or ""
    ptype = paper.get("type", "")

    lines = [f"@misc{{{key},"]
    if authors:
        lines.append(f"  author = {{{authors}}},")
    if title:
        lines.append(f"  title  = {{{{{title}}}}},")
    if year:
        lines.append(f"  year   = {{{year}}},")
    if doi:
        lines.append(f"  doi    = {{{doi}}},")
    if url:
        lines.append(f"  url    = {{{url}}},")
    if ptype:
        lines.append(f"  note   = {{Type: {ptype}}},")
    lines.append("}")
    return "\n".join(lines)


def main() -> None:
    """Load the references map and write paper/refs.bib."""
    refs = json.loads(_REF_MAP.read_text())
    papers = refs.get("papers", {})

    entries = []
    skipped = 0
    for key in sorted(papers):
        if key.startswith("_uncurated"):
            skipped += 1
            continue
        entries.append(_entry(key, papers[key]))

    content = _HEADER + "\n\n".join(entries) + "\n"
    _OUT.write_text(content)
    print(f"Written {_OUT} ({len(entries)} entries, {skipped} uncurated skipped)")


if __name__ == "__main__":
    main()
