"""Generate or check paper/snippets/*.tex from executed fdars snippets.

Each snippet runs REAL fdars code against a docs/data/ dataset, captures its
stdout, and emits a deterministic lstlisting fragment (source + output) that
the paper manuscript ``\\input``s.

Usage
-----
Generate mode (writes paper/snippets/*.tex)::

    PYTHONPATH=scripts:paper/code python paper/code/gen_snippets.py

Check mode (exits 1 if any committed fragment is stale or missing)::

    PYTHONPATH=scripts:paper/code python paper/code/gen_snippets.py --check

Macro set
---------
Generated fragments are consumed by ``paper/sections/capabilities.tex`` via
``\\input{snippets/<name>}``.  Each fragment contains:

- A static banner (no date/timestamp for byte-stable re-runs).
- A ``lstlisting[style=fdarsinput]`` block with the self-contained snippet
  source (imports included so readers can copy-paste).
- A ``lstlisting[style=fdarsoutput]`` block with the captured stdout, when
  the snippet produces non-empty output.

Determinism rules
-----------------
1. No timestamps in the banner — static text only.
2. Stochastic snippets seed ``np.random.seed`` before any random call.
3. Captured output uses shapes, dict keys, rounded scalars — never raw
   float arrays (platform-dependent repr).
4. Dict/list ordering: insertion-order-stable (Python 3.7+).
5. Single trailing ``\\n``, UTF-8, LF line endings.

Requires a compiled fdars (maturin develop) on PYTHONPATH.
"""
from __future__ import annotations

import io
import sys
import textwrap
from contextlib import redirect_stdout
from pathlib import Path

# Path is resolved relative to __file__, not CWD — safe to invoke from any directory.
_SNIPPETS_DIR = Path(__file__).resolve().parent.parent / "snippets"
_BANNER = "% AUTO-GENERATED by paper/code/gen_snippets.py -- do not edit."


def _run(source: str, name: str = "<snippet>", extra_ns: dict | None = None) -> str:
    """Exec *source* in a fresh namespace and return captured stdout verbatim.

    Parameters
    ----------
    source : str
        Python source code to execute.
    name : str, optional
        Filename passed to ``compile()`` — used in tracebacks to identify
        which snippet failed.  Defaults to ``"<snippet>"`` for backwards
        compatibility; pass the snippet key name in production to get
        ``File "<snippet:represent>", line N`` in CI failure output.
    extra_ns : dict, optional
        Extra names injected into the execution namespace before exec (e.g.
        ``data_path`` from paper_utils so snippets use a robust data accessor).

    Returns
    -------
    str
        Captured stdout produced by the snippet (may be empty).
    """
    ns: dict = {}
    if extra_ns:
        ns.update(extra_ns)
    buf = io.StringIO()
    with redirect_stdout(buf):
        exec(compile(textwrap.dedent(source), f"<snippet:{name}>", "exec"), ns)  # noqa: S102
    return buf.getvalue()


def _render(source: str, output: str) -> str:
    """Render snippet source + captured output as a LaTeX lstlisting fragment.

    Parameters
    ----------
    source : str
        Snippet source code (dedented; leading/trailing blank lines stripped).
    output : str
        Captured stdout (may be empty — output block is omitted if so).

    Returns
    -------
    str
        Full ``.tex`` fragment content ending with a single trailing newline.
        Byte-stable across runs (no timestamps, deterministic structure).
    """
    src = textwrap.dedent(source).strip("\n")
    lines = [
        _BANNER,
        r"\begin{lstlisting}[language=Python,style=fdarsinput]",
        src,
        r"\end{lstlisting}",
    ]
    if output.strip():
        lines += [
            r"\begin{lstlisting}[style=fdarsoutput]",
            output.rstrip("\n"),
            r"\end{lstlisting}",
        ]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Shared data-accessor injected into every snippet namespace so snippets are
# robust to cwd (PIPE-01 lock: no dataset copied into paper/).
# ---------------------------------------------------------------------------
from paper_utils import data_path as _data_path  # noqa: E402


_EXTRA_NS = {"data_path": _data_path}

# ---------------------------------------------------------------------------
# Snippet registry.
#
# Each entry: (name, source-code-string).
#
# Rules per RESEARCH.md §Determinism:
#   - Keep imports INSIDE the snippet body (self-contained, copy-pasteable).
#   - Use data_path("growth.csv") (injected into exec namespace).
#   - Avoid raw float arrays in print() — use shapes, keys, rounded scalars.
#   - Seed any stochastic call (np.random.seed / seed= kwarg).
#
# Wave-2 plans (88-02) will append additional family entries here.
# ---------------------------------------------------------------------------
SNIPPETS: list[tuple[str, str]] = [
    # ------------------------------------------------------------------
    # 1. Represent (data model) — tracer snippet for Phase 88 Plan 01.
    #    Validates the full harness path: script -> exec -> .tex -> \input.
    #    growth.csv: 31 ages x 93 subjects; .values.T -> (93 obs, 31 pts).
    # ------------------------------------------------------------------
    ("represent", """\
        import numpy as np, pandas as pd
        from fdars import Fdata
        growth = pd.read_csv(data_path("growth.csv"), index_col=0)
        ARG = growth.index.values.astype(float)
        X = growth.values.T.astype(np.float64)
        fd = Fdata(X, argvals=ARG,
                   names={"x": "Age (years)", "y": "Height (cm)"})
        print(repr(fd))
        print("mean shape:", fd.mean().shape)
        """),
    # ------------------------------------------------------------------
    # 2. Basis / smoothing — fdata_to_basis_1d returns (coefs, nbasis) TUPLE;
    #    smooth_basis_gcv returns a dict.
    #    growth.csv setup: X (93, 31) float64, ARG len 31.
    # ------------------------------------------------------------------
    ("basis", """\
        import numpy as np, pandas as pd
        import fdars
        growth = pd.read_csv(data_path("growth.csv"), index_col=0)
        ARG = growth.index.values.astype(float)
        X = growth.values.T.astype(np.float64)
        res = fdars.basis.fdata_to_basis_1d(
            X[:5], ARG, n_basis=8, basis_type="bspline")
        coefs, nbasis = res
        print("coefficients shape:", coefs.shape, "| n_basis:", nbasis)
        sm = fdars.basis.smooth_basis_gcv(
            X[:5], ARG, n_basis=8, basis_type="bspline")
        print("smoothing keys:", list(sm.keys()))
        print("fitted shape:", sm["fitted"].shape)
        """),
    # ------------------------------------------------------------------
    # 3. Depth & outliers — use Fdata.depth() method (handles dtype);
    #    muod(data) takes NO argvals.
    # ------------------------------------------------------------------
    ("depth", """\
        import numpy as np, pandas as pd
        import fdars
        from fdars import Fdata
        growth = pd.read_csv(data_path("growth.csv"), index_col=0)
        ARG = growth.index.values.astype(float)
        X = growth.values.T.astype(np.float64)
        fd = Fdata(X, argvals=ARG)
        depths = fd.depth(method="fraiman_muniz")
        print("depths shape:", depths.shape)
        print("most central obs:", int(np.argmax(depths)))
        out = fdars.outliers.muod(X)
        print("shape outliers:", out["shape_outliers"])
        print("amplitude outliers:", out["amplitude_outliers"])
        """),
    # ------------------------------------------------------------------
    # 4. FPCA (dense) + sparse/irregular PACE FPCA.
    #    This doubles as the MANU-05 irregular-representation snippet.
    #    pace_fpca.irreg_fdata_from_lists -> PyIrregFdata -> pace_fpca().
    # ------------------------------------------------------------------
    ("fpca", """\
        import numpy as np, pandas as pd
        from fdars import Fdata
        from fdars.pace_fpca import irreg_fdata_from_lists, pace_fpca
        growth = pd.read_csv(data_path("growth.csv"), index_col=0)
        ARG = growth.index.values.astype(float)
        X = growth.values.T.astype(np.float64)
        fd = Fdata(X, argvals=ARG)
        pc = fd.to_pc(n_comp=3)
        sv = np.round(pc["singular_values"], 2).tolist()
        print("FPCA scores shape:", pc["scores"].shape)
        print("singular values:", sv)
        np.random.seed(42)
        sizes = np.random.randint(5, 15, size=30)
        argvals_list = [
            np.sort(np.random.uniform(1, 18, s)).tolist() for s in sizes
        ]
        values_list = [np.sin(av).tolist() for av in argvals_list]
        irreg = irreg_fdata_from_lists(argvals_list, values_list)
        pace = pace_fpca(irreg, ncomp=2)
        print("PACE scores shape:", pace["scores"].shape)
        print("ncomp:", pace["ncomp"])
        """),
    # ------------------------------------------------------------------
    # 5. Clustering — kmeans_fd(data, argvals, k, seed=42); print
    #    cluster sizes (int list) and converged (bool), not float tot_withinss.
    # ------------------------------------------------------------------
    ("clustering", """\
        import numpy as np, pandas as pd
        import fdars
        growth = pd.read_csv(data_path("growth.csv"), index_col=0)
        ARG = growth.index.values.astype(float)
        X = growth.values.T.astype(np.float64)
        km = fdars.clustering.kmeans_fd(X, ARG, k=3, seed=42)
        print("cluster sizes:", np.bincount(km["cluster"]).tolist())
        print("converged:", km["converged"])
        """),
    # ------------------------------------------------------------------
    # 6. Classification — fclassif_knn(data, labels, ncomp, k);
    #    labels MUST be int64 ndarray (not list, not uint32);
    #    phoneme.csv: 400 rows x 256 freq points, 5 classes in row index.
    # ------------------------------------------------------------------
    ("classification", """\
        import numpy as np, pandas as pd
        import fdars
        ph = pd.read_csv(data_path("phoneme.csv"), index_col=0)
        Xp = ph.values.astype(np.float64)
        labels_str = ph.index.tolist()
        uniq = list(dict.fromkeys(labels_str))
        lut = {l: i for i, l in enumerate(uniq)}
        y = np.array([lut[l] for l in labels_str], dtype=np.int64)
        res = fdars.classification.fclassif_knn(
            Xp[:100], y[:100], ncomp=3, k=5)
        print("accuracy:", res["accuracy"])
        """),
    # ------------------------------------------------------------------
    # 7. Regression (scalar-on-function) — fregre_lm(data, response, n_comp);
    #    tecator.csv: 240 x 103 (100 spectral channels + moisture/fat/protein).
    #    FoF regression (fof_regression) is available but mentioned in prose.
    # ------------------------------------------------------------------
    ("regression", """\
        import numpy as np, pandas as pd
        import fdars
        tec = pd.read_csv(data_path("tecator.csv"), index_col=0)
        Xt = tec.iloc[:, :100].values.astype(np.float64)
        yfat = tec["fat"].values.astype(np.float64)
        sof = fdars.regression.fregre_lm(Xt, yfat, n_comp=5)
        print("R^2:", round(sof["r_squared"], 4))
        """),
    # ------------------------------------------------------------------
    # 8. Functional time series — ftsm_forecast(data, argvals, h, ncomp);
    #    NOTE: takes RAW data+argvals, NOT a fitted ftsm model dict.
    #    pm10_graz.csv: 48 half-hours x 182 consecutive days -> .T -> (182, 48).
    #    A genuine functional time series: each curve is one day's diurnal PM10
    #    profile, so forecasting the next day's curve is substantive. sqrt is
    #    the standard variance-stabilising transform for this dataset.
    # ------------------------------------------------------------------
    ("fts", """\
        import numpy as np, pandas as pd
        import fdars
        pm = pd.read_csv(data_path("pm10_graz.csv"), index_col=0)
        X = pm.T.values.astype(np.float64)        # 182 days x 48 half-hours
        ARG = pm.index.values.astype(np.float64)  # half-hour intervals
        fc = fdars.fts.ftsm_forecast(np.sqrt(X), ARG, h=3, ncomp=3)
        print("forecast shape:", fc["forecast"].shape, "| h:", fc["h"])
        """),
    # ------------------------------------------------------------------
    # 9. SPM — spm_phase1 then spm_monitor with UNPACKED positional args
    #    (NOT the result dict). Print alarm counts as ints.
    # ------------------------------------------------------------------
    ("spm", """\
        import numpy as np, pandas as pd
        import fdars
        growth = pd.read_csv(data_path("growth.csv"), index_col=0)
        ARG = growth.index.values.astype(float)
        X = growth.values.T.astype(np.float64)
        p1 = fdars.spm.spm_phase1(X[:46], ARG, ncomp=3, alpha=0.05)
        mon = fdars.spm.spm_monitor(
            p1["mean"], p1["loadings"], p1["weights"],
            p1["eigenvalues"], p1["t2_limit"], p1["spe_limit"],
            X[46:], ARG,
        )
        print("T2 alarms:", int(mon["t2_alarm"].sum()))
        print("SPE alarms:", int(mon["spe_alarm"].sum()))
        """),
    # ------------------------------------------------------------------
    # 10. Conformal / tolerance — fpca_tolerance_band(data, ncomp, nb, coverage, seed);
    #     NO argvals, NO alpha kwarg (use coverage=). Seeded -> deterministic.
    # ------------------------------------------------------------------
    ("tolerance", """\
        import numpy as np, pandas as pd
        import fdars
        growth = pd.read_csv(data_path("growth.csv"), index_col=0)
        ARG = growth.index.values.astype(float)
        X = growth.values.T.astype(np.float64)
        tol = fdars.tolerance.fpca_tolerance_band(
            X, ncomp=3, nb=200, coverage=0.95, seed=42)
        print("tolerance keys:", list(tol.keys()))
        print("band half-width shape:", tol["half_width"].shape)
        """),
    # ------------------------------------------------------------------
    # 11. Density / Frechet / metric — lp_self_1d + dtw_self_1d;
    #     dtw_self_1d(data) takes NO argvals. Round DTW float for stability.
    #     frechet_mean / density_fda.wasserstein_barycenter covered in prose.
    # ------------------------------------------------------------------
    ("metric", """\
        import numpy as np, pandas as pd
        import fdars
        growth = pd.read_csv(data_path("growth.csv"), index_col=0)
        ARG = growth.index.values.astype(float)
        X = growth.values.T.astype(np.float64)
        D = fdars.metric.lp_self_1d(X, ARG, p=2.0)
        print("L2 distance matrix shape:", D.shape)
        Ddtw = fdars.metric.dtw_self_1d(X[:10])
        print("DTW[0,1]:", round(float(Ddtw[0, 1]), 2))
        """),
    # ------------------------------------------------------------------
    # 12. Alignment (elastic) — the classic Ramsay-Silverman example: register
    #     growth-VELOCITY curves so the pubertal-spurt peak (which occurs at
    #     different ages) lines up. Smooth -> differentiate -> karcher_mean.
    #     Berkeley girls (cols 39:93). Deterministic (no RNG).
    # ------------------------------------------------------------------
    ("alignment", """\
        import numpy as np, pandas as pd
        import fdars
        from fdars import Fdata
        growth = pd.read_csv(data_path("growth.csv"), index_col=0)
        ARG = growth.index.values.astype(float)
        girls = growth.values.T[39:].astype(np.float64)   # 54 Berkeley girls
        # Smooth to B-spline coefficients, re-evaluate on a DENSE age grid
        # (the 31-age grid is too coarse for a stable velocity), then differentiate.
        sm = fdars.basis.smooth_basis_gcv(
            girls, ARG, n_basis=12, basis_type="bspline")
        dense = np.linspace(ARG.min(), ARG.max(), 120)
        fit = fdars.basis.basis_to_fdata_1d(
            sm["coefficients"], dense, 12, "bspline")
        vel = Fdata(fit, argvals=dense).deriv().data
        # Elastic registration of the velocity curves (aligns the spurt peak).
        res = fdars.alignment.karcher_mean(vel, dense, max_iter=50)
        print("karcher keys:", list(res.keys()))
        print("aligned shape:", res["aligned_data"].shape)
        print("warping gammas:", res["gammas"].shape)
        """),
    # ------------------------------------------------------------------
    # 13. Advisor (LLM-free diagnostics) — build_diagnostics(result, method);
    #     DO NOT call advise() (needs LLM, non-deterministic, needs API key).
    #     build_diagnostics is offline and deterministic.
    # ------------------------------------------------------------------
    ("advisor_diag", """\
        import numpy as np, pandas as pd
        import fdars
        from fdars import Fdata
        growth = pd.read_csv(data_path("growth.csv"), index_col=0)
        ARG = growth.index.values.astype(float)
        X = growth.values.T.astype(np.float64)
        fd = Fdata(X, argvals=ARG)
        pc = fd.to_pc(n_comp=3)
        diag = fdars.advisor.build_diagnostics(pc, "fpca", argvals=ARG)
        cum = np.round(diag["cumulative_variance_explained"], 3).tolist()
        print("cumulative variance explained:", cum)
        """),
    # ------------------------------------------------------------------
    # 14. sklearn estimator layer — FPCATransformer from _skeletons (NOT
    #     re-exported at fdars.sklearn top level); param is n_components NOT n_comp.
    #     Pipeline with RidgeCV on tecator; round mean R^2 for float stability.
    # ------------------------------------------------------------------
    ("sklearn", """\
        import numpy as np, pandas as pd
        from fdars.sklearn._skeletons import FPCATransformer
        from sklearn.pipeline import Pipeline
        from sklearn.linear_model import RidgeCV
        from sklearn.model_selection import cross_val_score
        tec = pd.read_csv(data_path("tecator.csv"), index_col=0)
        Xt = tec.iloc[:, :100].values.astype(np.float64)
        yfat = tec["fat"].values.astype(np.float64)
        pipe = Pipeline([
            ("fpca", FPCATransformer(n_components=5)),
            ("ridge", RidgeCV()),
        ])
        scores = cross_val_score(pipe, Xt, yfat, cv=5, scoring="r2")
        print("mean R^2 (5-fold):", round(float(scores.mean()), 3))
        """),
]


def main() -> None:
    """Entry point: generate or drift-check all snippet fragments."""
    check = "--check" in sys.argv
    _SNIPPETS_DIR.mkdir(parents=True, exist_ok=True)
    stale: list[str] = []

    for name, source in SNIPPETS:
        out = _run(source, name=name, extra_ns=_EXTRA_NS)
        content = _render(source, out)
        target = _SNIPPETS_DIR / f"{name}.tex"

        if check:
            if not target.exists() or target.read_text(encoding="utf-8") != content:
                stale.append(str(target))
        else:
            target.write_text(content, encoding="utf-8")

    if check:
        if stale:
            print(
                "DRIFT: stale/missing snippets -- re-run gen_snippets.py and commit:",
                file=sys.stderr,
            )
            for s in stale:
                print(f"  {s}", file=sys.stderr)
            sys.exit(1)
        print("gen_snippets: OK (no drift)")
    else:
        print(f"Wrote {len(SNIPPETS)} snippet fragment(s) to {_SNIPPETS_DIR}")


if __name__ == "__main__":
    main()
